/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package gradle.lib;

import static org.junit.jupiter.api.Assertions.assertEquals;

import org.junit.jupiter.api.Test;

import gradle.lib.EndianReader.ByteOrder;

class EndianReaderTest {

    @Test
    void testReader_BigEndian(){
        EndianReader reader = new EndianReader("The quick brown fox", ByteOrder.BIG_ENDIAN);
        
        byte[] theBytes = new byte[3];
        byte[] restOfBytes = new byte[16];
        reader.read(theBytes);
        reader.read(restOfBytes);

        assertEquals("The", new String(theBytes));
        assertEquals(" quick brown fox", new String(restOfBytes));
    }

    @Test
    void testReader_LittlEndian(){
        EndianReader reader = new EndianReader("The quick brown fox", ByteOrder.LITTLE_ENDIAN);
        
        byte[] xofBytes = new byte[3];
        byte[] restOfBytes = new byte[16];
        reader.read(xofBytes);
        reader.read(restOfBytes);


        assertEquals("fox", new String(xofBytes));
        assertEquals("The quick brown ", new String(restOfBytes));
    }

    @Test
    public void byteTest(){
        byte[] foxBytes = "fox".getBytes();

        assertEquals("fox", new String(foxBytes));
        byte[] f = {foxBytes[0]};
        byte[] o = {foxBytes[1]};
        byte[] x = {foxBytes[2]};


        assertEquals("f", new String(f));
        assertEquals("o", new String(o));
        assertEquals("x", new String(x));

    }
}
