/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package gradle.hello;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class AppTest {
    @Test void appHasAGreeting() {
        App classUnderTest = new App();
        assertNotNull(classUnderTest.getGreeting(), "app should have a greeting");
    }

    @Test void simpleTest() throws InterruptedException{

        int a = 5;

        Thread.sleep(10000);
        
        int b = a + 2;

        System.out.println("hello world ben test");

        assertEquals(b, 5);
    }
}
